# Generated by Django 2.2.2 on 2019-06-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('subpart', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('target', models.URLField(max_length=2000)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
