# docker-compose.yml
# The database has a state, so we don’t put it in a container.

version: '2'
services:
  shortener:
    build: .
    ports:
     - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - redis
  redis:
    image: redis
  celery:
    build: . # Don't use extends due to port conflicts.
    environment:
      - DATABASE_URL=${DATABASE_URL}
    command: celery worker -A project --loglevel=info --concurrency=4
    depends_on:
      - redis
  celery-beat:
    build: . # Don't use extends due to port conflicts.
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - redis
    command: celery -A project beat -l info